/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PsychologyConsultationManagementSystem;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class LecturerMenu extends javax.swing.JFrame {
    public String lecID;
    /**
     * Creates new form LecturerMenu
     */
    public LecturerMenu(String lecID) {
        if (lecID==""){
            JOptionPane.showMessageDialog(null,"Please login to access to this page.","Alert",JOptionPane.WARNING_MESSAGE);
            new LecturerLogin();
            return;
        }
        initComponents();
        this.lecID=lecID;
        completedBtn.setEnabled(false);
        studentinfoBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        approveBtn.setEnabled(false);
        proposeBtn.setEnabled(false);
        checkFeedbackBtn.setEnabled(false);
        slotsTable.getColumnModel().getColumn(0).setWidth(0);
        slotsTable.getColumnModel().getColumn(0).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(0).setMaxWidth(0); 
        slotsTable.getColumnModel().getColumn(1).setWidth(0);
        slotsTable.getColumnModel().getColumn(1).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(1).setMaxWidth(0);
        slotsTable.getColumnModel().getColumn(5).setWidth(0);
        slotsTable.getColumnModel().getColumn(5).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(5).setMaxWidth(0);
        slotsTable.getColumnModel().getColumn(6).setWidth(0);
        slotsTable.getColumnModel().getColumn(6).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(6).setMaxWidth(0);
        refreshApp();
        setLocationRelativeTo(null);
        setVisible(true);

    }

    public String getLecID() {
        return lecID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        slotsTable = new javax.swing.JTable();
        scheduledBox = new javax.swing.JCheckBox();
        bookedBox = new javax.swing.JCheckBox();
        reschedulingBox = new javax.swing.JCheckBox();
        completedBox = new javax.swing.JCheckBox();
        canceledBox = new javax.swing.JCheckBox();
        CreateSlot = new javax.swing.JButton();
        completedBtn = new javax.swing.JButton();
        studentinfoBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        proposeBtn = new javax.swing.JButton();
        rescheduledBox = new javax.swing.JCheckBox();
        logoutBtn = new javax.swing.JButton();
        checkFeedbackBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        viewProfileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slotsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Consultation ID", "Student", "Date", "Time", "Duration (min)", "Lecturer Feedback", "Student Feedback", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        slotsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        slotsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slotsTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(slotsTable);

        scheduledBox.setSelected(true);
        scheduledBox.setText("Scheduled");
        scheduledBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduledBoxActionPerformed(evt);
            }
        });

        bookedBox.setSelected(true);
        bookedBox.setText("Booked");
        bookedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookedBoxActionPerformed(evt);
            }
        });

        reschedulingBox.setSelected(true);
        reschedulingBox.setText("Rescheduling");
        reschedulingBox.setToolTipText("");
        reschedulingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reschedulingBoxActionPerformed(evt);
            }
        });

        completedBox.setSelected(true);
        completedBox.setText("Completed");
        completedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedBoxActionPerformed(evt);
            }
        });

        canceledBox.setSelected(true);
        canceledBox.setText("Canceled");
        canceledBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceledBoxActionPerformed(evt);
            }
        });

        CreateSlot.setText("Create Slot");
        CreateSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSlotActionPerformed(evt);
            }
        });

        completedBtn.setText("Completed");
        completedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedBtnActionPerformed(evt);
            }
        });

        studentinfoBtn.setText("Student Info");
        studentinfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentinfoBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        proposeBtn.setText("Propose time");
        proposeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposeBtnActionPerformed(evt);
            }
        });

        rescheduledBox.setSelected(true);
        rescheduledBox.setText("Rescheduled");
        rescheduledBox.setToolTipText("");
        rescheduledBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescheduledBoxActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        checkFeedbackBtn.setText("Check Feedback");
        checkFeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFeedbackBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        viewProfileBtn.setText("View Profile");
        viewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reschedulingBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scheduledBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookedBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(completedBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(canceledBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rescheduledBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentinfoBtn)
                                    .addComponent(completedBtn)
                                    .addComponent(checkFeedbackBtn)
                                    .addComponent(cancelBtn)
                                    .addComponent(approveBtn)
                                    .addComponent(proposeBtn))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(CreateSlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scheduledBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookedBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reschedulingBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rescheduledBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canceledBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentinfoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkFeedbackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(approveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proposeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateSlot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProfileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshApp(){
        completedBtn.setEnabled(false);
        String lecID = getLecID();
        String path="";
        DefaultTableModel model = (DefaultTableModel) slotsTable.getModel();
        model.setRowCount(0);
        path = "consultation.txt";
        boolean scheduled = scheduledBox.isSelected();
        boolean booked = bookedBox.isSelected();
        boolean rescheduling = reschedulingBox.isSelected();
        boolean rescheduled = rescheduledBox.isSelected();
        boolean completed = completedBox.isSelected();
        boolean canceled = canceledBox.isSelected();
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            String status;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                // Split the line by commas (or any other delimiter)
                rowData = line.split(",");
                status = rowData[8].trim();
                String[] takeData = {rowData[0],rowData[2],rowData[3],rowData[4],rowData[5],rowData[6],rowData[7],rowData[8]};
                if (rowData[1].trim().equals(lecID)){
                    if (status.equals("Scheduled") && scheduled){
                        model.addRow(takeData);
                    }else if (status.equals("Booked") && booked){
                        model.addRow(takeData);
                    }else if (status.equals("Rescheduling") && rescheduling){
                        model.addRow(takeData);
                    }else if (status.equals("Rescheduled") && rescheduled){
                        model.addRow(takeData);
                    }else if (status.equals("Completed") && completed){
                        model.addRow(takeData);
                    }else if (status.equals("Canceled") && canceled){
                        model.addRow(takeData);
                    }   
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading file!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        completedBtn.setEnabled(false);
        studentinfoBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        approveBtn.setEnabled(false);
    }
    
    private void slotsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotsTableMousePressed
        int row = slotsTable.getSelectedRow();
        String status = slotsTable.getModel().getValueAt(row, 7).toString().trim();
//        String stuFeedback = slotsTable.getModel().getValueAt(row, 5).toString().trim();
        if (status.equals("Booked")){
            completedBtn.setEnabled(true);
            studentinfoBtn.setEnabled(true);
            cancelBtn.setEnabled(false);
            approveBtn.setEnabled(false);
            proposeBtn.setEnabled(false);
            checkFeedbackBtn.setEnabled(false);
        }else if (status.equals("Completed")){
            studentinfoBtn.setEnabled(true);
            checkFeedbackBtn.setEnabled(true);
            completedBtn.setEnabled(false);
            cancelBtn.setEnabled(false);
            approveBtn.setEnabled(false);
            proposeBtn.setEnabled(false);
        }else if (status.equals("Scheduled")){
            cancelBtn.setEnabled(true);
            completedBtn.setEnabled(false);
            studentinfoBtn.setEnabled(false);
            approveBtn.setEnabled(false);
            proposeBtn.setEnabled(false);
            checkFeedbackBtn.setEnabled(false);
        }else if (status.equals("Rescheduling")){
            approveBtn.setEnabled(true);
            proposeBtn.setEnabled(true);
            cancelBtn.setEnabled(true);
            completedBtn.setEnabled(false);
            studentinfoBtn.setEnabled(true);
            checkFeedbackBtn.setEnabled(false);
        }else if (status.equals("Rescheduled")){
            approveBtn.setEnabled(false);
            proposeBtn.setEnabled(false);
            cancelBtn.setEnabled(true);
            completedBtn.setEnabled(true);
            studentinfoBtn.setEnabled(true);
            checkFeedbackBtn.setEnabled(false);
        }else if (status.equals("Canceled")){
            completedBtn.setEnabled(false);
            studentinfoBtn.setEnabled(true);
            cancelBtn.setEnabled(false);
            approveBtn.setEnabled(false);
            proposeBtn.setEnabled(false);
            checkFeedbackBtn.setEnabled(false);
        }
    }//GEN-LAST:event_slotsTableMousePressed

    private void bookedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookedBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_bookedBoxActionPerformed

    private void CreateSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSlotActionPerformed
        String lecID = getLecID();
        CreateSlot page = new CreateSlot(lecID);
        page.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                refreshApp();
            }
        });
    }//GEN-LAST:event_CreateSlotActionPerformed

    private void scheduledBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduledBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_scheduledBoxActionPerformed

    private void reschedulingBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reschedulingBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_reschedulingBoxActionPerformed

    private void completedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_completedBoxActionPerformed

    private void canceledBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceledBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_canceledBoxActionPerformed

    private void completedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedBtnActionPerformed
        String feedback = JOptionPane.showInputDialog(null,"Please provide a feedback:");
        if (!feedback.trim().equals("")){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            changeConsultation("Completed",consID,"",feedback);
        }
    }//GEN-LAST:event_completedBtnActionPerformed

    private void changeConsultation(String action, String consID, String dt, String fb){
        String path = "consultation.txt";
        String lecID = getLecID();
        String newContent="Consultation Slot ID, Lecturer ID, Student ID, Date, Time, Duration (min), Lecturer Feedback, Student Feedback, Status";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                if (rowData[0].equals(consID)){
                    line="";
                    String add="";
                    for (int i =0;i<rowData.length;i++){
                        if (i==rowData.length-1){
                            add=" "+action;
                        }else if (i==3 && dt!=""){
                            add=" "+dt+",";
                            i++;
                        }else if (i==6 && fb!=""){
                            add=" "+fb+",";
                        }else{
                            add=rowData[i]+",";
                        }
                        line=line+add;
                    }
                }
                newContent = newContent + "\n" + line;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try{
            FileWriter writer = new FileWriter(path, false);
            writer.write(newContent);
            writer.close();
        }catch (IOException e) {
            e.printStackTrace();
        }
        refreshApp();
    }
    
    private void studentinfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentinfoBtnActionPerformed
        int row = slotsTable.getSelectedRow();
        String stuID = slotsTable.getModel().getValueAt(row, 1).toString();
        String path = "users.txt";
        String name="";
        String email="";
        String phone="";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                // Split the line by commas (or any other delimiter)
                rowData = line.split(",");
                if (rowData[0].equals(stuID.trim())){
                    name = rowData[2].trim();
                    email = rowData[5].trim();
                    phone = rowData[6].trim();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        String info=String.format("Name: %s \nEmail: %s \nPhone Number: %s",name,email,phone);
        JOptionPane.showMessageDialog(null,info);  
    }//GEN-LAST:event_studentinfoBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm reschedule to proposed date and time?","Confirmation",dialogButton);
        if (dialogResult==0){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            changeConsultation("Booked",consID,"","");
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm cancel slot?","Confirmation",dialogButton);
        if (dialogResult==0){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            changeConsultation("Canceled",consID,"","");
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void proposeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposeBtnActionPerformed
        String lecID = getLecID();
        int row = slotsTable.getSelectedRow();
        String consID = slotsTable.getModel().getValueAt(row, 0).toString();
        ProposeTime page = new ProposeTime(lecID,consID,"Rescheduled");
        page.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                refreshApp();
            }
        });
    }//GEN-LAST:event_proposeBtnActionPerformed

    private void rescheduledBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescheduledBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_rescheduledBoxActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Confirmation",dialogButton);
        if (dialogResult==0){
            setVisible(false);
            new LecturerLogin();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void checkFeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFeedbackBtnActionPerformed
        int row = slotsTable.getSelectedRow();
        String feedback = slotsTable.getModel().getValueAt(row, 6).toString();
        if (feedback.trim().equals("-")){
            JOptionPane.showMessageDialog(null, "No feedback provided.");
        }else{
            JOptionPane.showMessageDialog(null, feedback);
        }
    }//GEN-LAST:event_checkFeedbackBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refreshApp();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void viewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBtnActionPerformed
        new Profile(getLecID()).setVisible(true);
    }//GEN-LAST:event_viewProfileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerMenu("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateSlot;
    private javax.swing.JButton approveBtn;
    private javax.swing.JCheckBox bookedBox;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox canceledBox;
    private javax.swing.JButton checkFeedbackBtn;
    private javax.swing.JCheckBox completedBox;
    private javax.swing.JButton completedBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton proposeBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JCheckBox rescheduledBox;
    private javax.swing.JCheckBox reschedulingBox;
    private javax.swing.JCheckBox scheduledBox;
    private javax.swing.JTable slotsTable;
    private javax.swing.JButton studentinfoBtn;
    private javax.swing.JButton viewProfileBtn;
    // End of variables declaration//GEN-END:variables
}
