/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PsychologyConsultationManagementSystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Profile extends javax.swing.JFrame {
    String ID;
    String name;
    String username;
    String email;
    String phone;

    public String getID() {
        return ID;
    }
    
    public String getName(){
        return name;
    }

    public String getUsername() {
        return username;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public void showCurrentInfo() {
        nameBox.setText(getName());
        usernameBox.setText(getUsername());
        emailBox.setText(getEmail());
        phoneBox.setText(getPhone());
    }
    
    public Profile(String userID) {
        this.ID=userID;
        initComponents();
        String path = "users.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                // Split the line by commas (or any other delimiter)
                rowData = line.split(",");
                if (rowData[0].equals(userID.trim())){
                    this.name = rowData[2].trim();
                    this.username = rowData[1].trim();
                    this.email = rowData[5].trim();
                    this.phone = rowData[6].trim();
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        showCurrentInfo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        usernameBox = new javax.swing.JTextField();
        emailBox = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        phoneBox = new javax.swing.JTextField();
        doneBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLbl.setText("Name:");

        usernameLbl.setText("Username:");

        emailLbl.setText("Email:");

        phoneLbl.setText("Phone Number:");

        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(doneBtn)
                .addGap(30, 30, 30)
                .addComponent(resetBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailLbl, nameLbl, phoneLbl, usernameLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn)
                    .addComponent(resetBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        showCurrentInfo();
    }//GEN-LAST:event_resetBtnActionPerformed

    boolean checkUsername(String username){
        String filePath = "users.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            line = br.readLine();
            String[] headerData = line.split(",");
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");
                if (rowData[1].trim().equals(username)){
                    JOptionPane.showMessageDialog(null,"This username existed. Please use another username!","Alert",JOptionPane.WARNING_MESSAGE); 
                    return false;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return true;
    }
    
    private void updateProfile(String newName, String newUsername, String newEmail, String newPhone){
        String path = "users.txt";
        String userID = getID();
        String newContent="User ID, Username, Name, Password, User Type, Email, Phone Number";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                if (rowData[0].equals(userID)){
                    line="";
                    String add="";
                    for (int i =0;i<rowData.length;i++){
                        if (i==6){
                            add=" "+newPhone;
                        }else if (i==1){
                            add=" "+newUsername+",";
                        }else if (i==2){
                            add=" "+newName+",";
                        }else if (i==5){
                            add=" "+newEmail+",";
                        }else{
                            add=rowData[i]+",";
                        }
                        line=line+add;
                    }
                }
                newContent = newContent + "\n" + line;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try{
            FileWriter writer = new FileWriter(path, false);
            writer.write(newContent);
            writer.close();
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        String newUsername=usernameBox.getText().trim();
        String newName=nameBox.getText().trim();
        String newEmail=emailBox.getText().trim();
        String newPhone=phoneBox.getText().trim();
        if (! (newName.equals(getName()) && newUsername.equals(getUsername()) && newEmail.equals(getEmail()) && newPhone.equals(getPhone()) )){
            if (checkUsername(newUsername)){
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm changes?","Confirmation",dialogButton);
                if (dialogResult==0){
                    updateProfile(newName,newUsername,newEmail,newPhone);
                }
            }else{
                return;
            }
            
        }
        setVisible(false);
    }//GEN-LAST:event_doneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneBtn;
    private javax.swing.JTextField emailBox;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField nameBox;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField phoneBox;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField usernameBox;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
