/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PsychologyConsultationManagementSystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ProposeTime extends javax.swing.JFrame {
    public String userID;
    public String consID;
    public String mode;
    /**
     * Creates new form CreateSlot
     */
    public ProposeTime(String userID, String consID, String mode) {
        if (userID==""){
            JOptionPane.showMessageDialog(null,"Please navigate to this page through the login page.","Alert",JOptionPane.WARNING_MESSAGE);
            return;
        }
        this.userID=userID;
        this.consID=consID;
        this.mode=mode;
        initComponents();
        dateBox.setDate(new Date());
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public String getUserID() {
        return userID;
    }
    

    public String getConsID() {
        return consID;
    }

    public String getMode() {
        return mode;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLbl = new javax.swing.JLabel();
        hourBox = new javax.swing.JComboBox<>();
        minuteBox = new javax.swing.JComboBox<>();
        doneBtn = new javax.swing.JButton();
        timeLbl = new javax.swing.JLabel();
        dateBox = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dateLbl.setText("Date");

        hourBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));

        minuteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        timeLbl.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hourBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minuteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(timeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(doneBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeCons(String action, String consID, String dt){
        String path = "consultation.txt";
        String userID = getUserID();
        String newContent="Consultation Slot ID, Lecturer ID, Student ID, Date, Time, Duration (min), Lecturer Feedback, Student Feedback, Status";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                if (rowData[0].equals(consID)){
                    line="";
                    String add="";
                    for (int i =0;i<rowData.length;i++){
                        if (i==rowData.length-1){
                            add=" "+action;
                        }else if (i==3 && dt!=""){
                            add=" "+dt+",";
                            i++;
                        }else{
                            add=rowData[i]+",";
                        }
                        line=line+add;
                    }
                }
                newContent = newContent + "\n" + line;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try{
            FileWriter writer = new FileWriter(path, false);
        
            writer.write(newContent);
            
            writer.close();
        
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = dcn.format(dateBox.getDate());
        String hour = hourBox.getSelectedItem().toString();
        String minute = minuteBox.getSelectedItem().toString();
        String fullDateTime = date + " " + hour + ":" + minute + ":00";
        Date now = new Date();
        try{
            Date selectedDateTime = dtf.parse(fullDateTime);
            if (!selectedDateTime.before(now)){
                String time = hour + ":" + minute;
                String datetime = date+", "+time;
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm this schedule?","Confirmation",dialogButton);
                if (dialogResult==0){
                    String consID = getConsID();
                    String mode = getMode();
                    changeCons(mode,consID,datetime);
                    setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(null,"You cannot propose time in the past!","Alert",JOptionPane.WARNING_MESSAGE);  
            }
        }catch (Exception e){
            e.printStackTrace();
        } 
        
    }//GEN-LAST:event_doneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProposeTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProposeTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProposeTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProposeTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProposeTime("","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateBox;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton doneBtn;
    private javax.swing.JComboBox<String> hourBox;
    private javax.swing.JComboBox<String> minuteBox;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables
}
