/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PsychologyConsultationManagementSystem;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class StudentMenu extends javax.swing.JFrame {
    public String stuID;
    public int choice;

    /**
     * Creates new form StudentMenu
     */
    public StudentMenu(String stuID) {
        if (stuID==""){
            JOptionPane.showMessageDialog(null,"Please login to access to this page.","Alert",JOptionPane.WARNING_MESSAGE);
            new StudentLogin();
            return;
        }
        initComponents();
        this.stuID=stuID;
        makeConsBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        rescheBtn.setEnabled(false);
        checkFeedbackBtn.setEnabled(false);
        slotsTable.getColumnModel().getColumn(0).setWidth(0);
        slotsTable.getColumnModel().getColumn(0).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(0).setMaxWidth(0); 
        slotsTable.getColumnModel().getColumn(5).setWidth(0);
        slotsTable.getColumnModel().getColumn(5).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(5).setMaxWidth(0);
        slotsTable.getColumnModel().getColumn(6).setWidth(0);
        slotsTable.getColumnModel().getColumn(6).setMinWidth(0);
        slotsTable.getColumnModel().getColumn(6).setMaxWidth(0);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public String getStuID() {
        return stuID;
    }

    public int getChoice() {
        return choice;
    }

    public void setChoice(int choice) {
        this.choice = choice;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        slotsTable = new javax.swing.JTable();
        viewSlotBtn = new javax.swing.JButton();
        viewAppBtn = new javax.swing.JButton();
        makeConsBtn = new javax.swing.JButton();
        completedBox = new javax.swing.JCheckBox();
        incompleteBox = new javax.swing.JCheckBox();
        cancelBtn = new javax.swing.JButton();
        rescheBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();
        checkFeedbackBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        viewProfileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(543, 363));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        slotsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Consultation ID", "Lecturer", "Date", "Time", "Duration (min)", "Lecturer Feedback", "Student Feedback", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        slotsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        slotsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slotsTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(slotsTable);
        if (slotsTable.getColumnModel().getColumnCount() > 0) {
            slotsTable.getColumnModel().getColumn(2).setResizable(false);
            slotsTable.getColumnModel().getColumn(3).setResizable(false);
            slotsTable.getColumnModel().getColumn(4).setResizable(false);
            slotsTable.getColumnModel().getColumn(5).setResizable(false);
            slotsTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewSlotBtn.setText("View available slots");
        viewSlotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSlotBtnActionPerformed(evt);
            }
        });

        viewAppBtn.setText("View appointments");
        viewAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppBtnActionPerformed(evt);
            }
        });

        makeConsBtn.setText("Make consultation");
        makeConsBtn.setEnabled(false);
        makeConsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeConsBtnActionPerformed(evt);
            }
        });

        completedBox.setSelected(true);
        completedBox.setText("Completed");
        completedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedBoxActionPerformed(evt);
            }
        });

        incompleteBox.setSelected(true);
        incompleteBox.setText("Incomplete");
        incompleteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incompleteBoxActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setEnabled(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        rescheBtn.setText("Reschedule");
        rescheBtn.setEnabled(false);
        rescheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescheBtnActionPerformed(evt);
            }
        });

        feedbackBtn.setText("Feedback");
        feedbackBtn.setEnabled(false);
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });

        checkFeedbackBtn.setText("Check Feedback");
        checkFeedbackBtn.setEnabled(false);
        checkFeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFeedbackBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        viewProfileBtn.setText("View Profile");
        viewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProfileBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewAppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeConsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewSlotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(completedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(incompleteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rescheBtn)
                    .addComponent(feedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkFeedbackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSlotBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makeConsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewAppBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incompleteBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rescheBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feedbackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkFeedbackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProfileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSlotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSlotBtnActionPerformed
        makeConsBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        rescheBtn.setEnabled(false);
        feedbackBtn.setEnabled(false);
        checkFeedbackBtn.setEnabled(false);
        setChoice(1);
        loadFile();
    }//GEN-LAST:event_viewSlotBtnActionPerformed

    public String userName(String userID){
        String path = "users.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                // Split the line by commas (or any other delimiter)
                rowData = line.split(",");
                if (rowData[0].equals(userID.trim())){
                    String name = rowData[2];
                    return name;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "";
    }
    
    public void loadFile(){
        String path = "consultation.txt";
        DefaultTableModel model = (DefaultTableModel) slotsTable.getModel();
        model.setRowCount(0);
        
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                // Split the line by commas (or any other delimiter)
                rowData = line.split(",");                
                if (rowData[8].trim().equals("Scheduled")){
                    String name=userName(rowData[1]);
                    String[] takeData = {rowData[0],name,rowData[3],rowData[4],rowData[5],rowData[6],rowData[7],rowData[8]};
                    model.addRow(takeData);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading file!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void createAppointment(String consID){
        String path = "consultation.txt";
        String stuID = getStuID();
        String newContent="Consultation Slot ID, Lecturer ID, Student ID, Date, Time, Duration (min), Lecturer Feedback, Student Feedback, Status";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                if (rowData[0].equals(consID)){
                    line="";
                    String add="";
                    for (int i =0;i<rowData.length;i++){
                        if (i==2){
                            add=" "+stuID+",";
                        }else if (i==rowData.length-1){
                            add=" Booked";
                        }else{
                            add=rowData[i]+",";
                        }
                        line=line+add;
                    }
                }
                newContent = newContent +"\n" + line;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try{
            FileWriter writer = new FileWriter(path, false);
        
            writer.write(newContent);
            
            writer.close();
        
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void slotsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotsTableMousePressed
        if (getChoice()==1){
            makeConsBtn.setEnabled(true);
        }else if (getChoice()==2){
            int row = slotsTable.getSelectedRow();
            String status = slotsTable.getModel().getValueAt(row, 7).toString().trim();
            String stuFeedback = slotsTable.getModel().getValueAt(row, 6).toString().trim();
            if (status.equals("Booked")){
                cancelBtn.setEnabled(true);
                rescheBtn.setEnabled(true);
                feedbackBtn.setEnabled(false);
                checkFeedbackBtn.setEnabled(false);
            }else if (status.equals("Completed")){
                if (stuFeedback.equals("-")){
                    cancelBtn.setEnabled(false);
                    rescheBtn.setEnabled(false);
                    feedbackBtn.setEnabled(true);
                    checkFeedbackBtn.setEnabled(true);
                }else{
                    cancelBtn.setEnabled(false);
                    rescheBtn.setEnabled(false);
                    feedbackBtn.setEnabled(false);
                    checkFeedbackBtn.setEnabled(true);
                }                
            }else if (status.equals("Rescheduled")){
                cancelBtn.setEnabled(true);
                rescheBtn.setEnabled(false);
                feedbackBtn.setEnabled(false);
                checkFeedbackBtn.setEnabled(false);
            }else if (status.equals("Rescheduling")){
                cancelBtn.setEnabled(true);
                rescheBtn.setEnabled(false);
                feedbackBtn.setEnabled(false);
                checkFeedbackBtn.setEnabled(false);
            }else{
                cancelBtn.setEnabled(false);
                rescheBtn.setEnabled(false);
                feedbackBtn.setEnabled(false);
                checkFeedbackBtn.setEnabled(false);
            }
            
        }
        
    }//GEN-LAST:event_slotsTableMousePressed

    private void viewAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppBtnActionPerformed
        refreshApp();
    }

    private void refreshApp(){
        setChoice(2);
        makeConsBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
        rescheBtn.setEnabled(false);
        feedbackBtn.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) slotsTable.getModel();
        model.setRowCount(0);
        String path = "consultation.txt";
        String stuID = getStuID();
        String status;
        boolean past = completedBox.isSelected();
        boolean future = incompleteBox.isSelected();
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                status=rowData[8].trim();
                String name=userName(rowData[1]);
                String[] takeData = {rowData[0],name,rowData[3],rowData[4],rowData[5],rowData[6],rowData[7],rowData[8]};
                if (rowData[2].trim().equals(stuID)){
                    if ((status.equals("Booked") || status.equals("Rescheduling") || status.equals("Rescheduled") || status.equals("Canceled")) && future){
                        model.addRow(takeData);
                    }else if (status.equals("Completed") && past){
                        model.addRow(takeData);
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewAppBtnActionPerformed

    private void makeConsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeConsBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to confirm the booking?","Confirmation",dialogButton);
        if (dialogResult==0){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            createAppointment(consID);
            refreshApp();
        }
    }//GEN-LAST:event_makeConsBtnActionPerformed

    private void changeAppointment(String action, String consID, String dt, String fb){
        String path = "consultation.txt";
        String stuID = getStuID();
        String newContent="Consultation Slot ID, Lecturer ID, Student ID, Date, Time, Duration (min), Lecturer Feedback, Student Feedback, Status";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            String[] rowData;
            line = br.readLine();
            // Read file line by line
            while ((line = br.readLine()) != null) {
                rowData = line.split(",");
                if (rowData[0].equals(consID)){
                    line="";
                    String add="";
                    for (int i =0;i<rowData.length;i++){
                        if (i==rowData.length-1){
                            add=" "+action;
                        }else if (i==3 && dt!=""){
                            add=" "+dt+",";
                            i++;
                        }else if (i==7 && fb!=""){
                            add=" "+fb+",";
                        }else{
                            add=rowData[i]+",";
                        }
                        line=line+add;
                    }
                }
                newContent = newContent + "\n" + line;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        try{
            FileWriter writer = new FileWriter(path, false);
        
            writer.write(newContent);
            
            writer.close();
        
        }catch (IOException e) {
            e.printStackTrace();
        }
        refreshApp();
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel the appointment?","Confirmation",dialogButton);
        if (dialogResult==0){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            changeAppointment("Canceled",consID,"","");
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void rescheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescheBtnActionPerformed
        String stuID = getStuID();
        int row = slotsTable.getSelectedRow();
        String consID = slotsTable.getModel().getValueAt(row, 0).toString();
        String status = slotsTable.getModel().getValueAt(row, 7).toString().trim();
        ProposeTime page = new ProposeTime(stuID,consID,"Rescheduling");
        page.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                refreshApp();
            }
        });
    }//GEN-LAST:event_rescheBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        String feedback = JOptionPane.showInputDialog(null,"Please provide a feedback:");
        if (!feedback.trim().equals("")){
            int row = slotsTable.getSelectedRow();
            String consID = slotsTable.getModel().getValueAt(row, 0).toString();
            changeAppointment("Completed",consID,"",feedback);
        }
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void completedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_completedBoxActionPerformed

    private void checkFeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFeedbackBtnActionPerformed
        int row = slotsTable.getSelectedRow();
        String feedback = slotsTable.getModel().getValueAt(row, 5).toString();
        if (feedback.trim().equals("-")){
            JOptionPane.showMessageDialog(null, "No feedback provided.");
        }else{
            JOptionPane.showMessageDialog(null, feedback);
        }
    }//GEN-LAST:event_checkFeedbackBtnActionPerformed

    private void incompleteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incompleteBoxActionPerformed
        refreshApp();
    }//GEN-LAST:event_incompleteBoxActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Confirmation",dialogButton);
        if (dialogResult==0){
            setVisible(false);
            new StudentLogin();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBtnActionPerformed
        new Profile(getStuID()).setVisible(true);
    }//GEN-LAST:event_viewProfileBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMenu("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton checkFeedbackBtn;
    private javax.swing.JCheckBox completedBox;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JCheckBox incompleteBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton makeConsBtn;
    private javax.swing.JButton rescheBtn;
    private javax.swing.JTable slotsTable;
    private javax.swing.JButton viewAppBtn;
    private javax.swing.JButton viewProfileBtn;
    private javax.swing.JButton viewSlotBtn;
    // End of variables declaration//GEN-END:variables
}
